language: scala

scala:
  - 2.11.8

jdk:
 - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

before_script:
  - _JAVA_OPTIONS=

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts test
