language: scala

scala:
  - 2.11.8

jdk:
 - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx4g -J-XX:MaxPermSize=4g test
